# Generated by Django 2.1.2 on 2018-10-14 14:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 14, 14, 25, 28, 591762, tzinfo=utc)),
        ),
    ]
