# Generated by Django 2.1.2 on 2018-10-14 14:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_contact_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 14, 14, 26, 41, 790792, tzinfo=utc)),
        ),
    ]
